config/routes.rb
Rails.application.routes.draw do
  get "login" => 'session#new'
  post "login" => 'session#create'
  delete "logout" => 'session#destroy'


  resources :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
    has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

    def index
    end

    def show
        @admin = Admin.find_by id: params[:id]
    end
    
    def new
        @admin = Admin.new
    end

    def create

    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
    
  end

  def create
    admin = Admin.find_by name: params[:session][:name].downcase
    if admin && admin.authenticate(params[:session][:password])  #duoc cc boi has_secure_password
      flash[:success] = "Login Successfully"
      log_in admin
      redirect_to product

    else 
      flash[:danger] = "Invalid email/password combination"
      render :new
    end
  end

  def destroy
  end


end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/session_helper.rb
module SessionHelper

    def log_in admin
        session[:user_id] = admin.id
    end

    def log_out
        session.delete :user_id
    end
end

app/views/admins/new.html.erb
<div class="container">
    <div class="row">
        <h2 class="title"> Register new admin </h2>
    </div>

<div class="row">
    <div class="col-lg-offset-2">
        <%= form_for @admin, html: {class: "form-horizontal"} do |f| %>
            <div class="form-group">
                <%= f.label :name, "Name", class: "col-md-2 control-label"%>
                <div class="col-md-6">
                    <%= f.text_field :name, class: "form-control", placeholder: "Enter your name"%>
                </div>
            </div>

            <div class="form-group">
                <%= f.label :password, "Password", class: "col-md-2 control-label"%>
                <div class="col-md-6">
                    <%= f.text_field :password, class: "form-control", placeholder: "Enter your password"%>
                </div>
            </div>

            <div class="form-group">
                <%= f.label :password_confirmation, "Password", class: "col-md-2 control-label"%>
                <div class="col-md-6">
                    <%= f.text_field :password_confirmation, class: "form-control", placeholder: "Enter password confirmation"%>
                </div>
            </div>

            <div class="form-group">
                <div class="col-lg-offset-4">
                    <%= f.submit "Register", class: "btn btn-success"%>
                </div> 
            </div>
        <% end %>
    </div>
</div>
</div>

app/views/admins/show.html.erb
<%# <div class="container">
    <div class="row">

    </div>
</div> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManageProductsRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/header.html.erb
<nav class="navbar navbar-default horizon-navbar">
  <div class="container-fluid">
    <div class="navbar-header">
      <ol class="breadcrumb navbar-brand" style="background-color: transparent !important;">
      </ol>
    </div>

    <div class="text-right userbar">
      <span class="user-noti">
        <i class="ti-bell"></i>
      </span>
      <span class="user-id"> Hello <i>"hanhnt"</i> </span>
      <!--can u change this line into username : -->
      <button type="button" class="btn btn-primary btn-fill mt-2 mr-3" id="log-out">Log out</button>
    </div>
  </div>
</nav>

app/views/layouts/sidebar.html.erb
<div class="sidebar" data-background-color="brown" data-active-color="info">
    <!-- Logo -->

    <div class="logo">
        <a href="/" class="simple-text logo-normal text-center">
            <b>Admin</b>
        </a>
    </div>

    <div class="sidebar-wrapper">
        <ul class="nav">
            <!-- Products -->
            <li class="title == 'Main | Admin'">
                <a href="/main" class="nav-link">
                    <i class="ti-home"></i>
                    <p>Home</p>
                </a>
            </li>
            <li class=" title == 'Products | Admin'">
                <a href="/products" class="nav-link">
                    <i class="ti-package"></i>
                    <p>Products</p>
                </a>
            </li>
            <!-- Orders -->
            <li class=" title == 'Orders | Chart' ">
                <a href="/orders" class="nav-link">
                    <i class="ti-settings"></i>
                    <p>Orders</p>
                </a>
            </li>
        </ul>
    </div>
</div>

app/views/session/new.html.erb
<div class="container">
    <div class="row">
        <h1 class="title"> Login </h1>
    </div>

    <div class="row">
        <div class="col-lg-offset-3 col-lg-6">
            <%= form_for :session, url: login_path do |f| %>
                <div class="form-group">
                    <%= f.label :name %>
                    <%= f.text_field :name, placeholder: "Enter your name", class: "form-control" %>
                </div>

                <div class="form-group">
                    <%= f.label :password %>
                    <%= f.text_field :password, placeholder: "Enter your password", class: "form-control"%>
                </div>

                <div class="text-center">
                    <%= f.submit "login", class: "btn btn-info col-lg-12"%>
                </div>

                <div class="text-right">
                    <%= link_to "Register", new_admin_path %>
                </div>
            <% end %>
        </div>
    </div>
</div>